#include"functions.h"


struct BirdInstance allBirds[10] = {
    {.model = birdDex[Wing_G],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Wing_G],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Wing_G],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Wing_G],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Speed_E],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Speed_E],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Steal_T],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Steal_T],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Big_O],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
    {.model = birdDex[Lead_R],
     .posX = 0x10,
     .posY = 0x00,
     .status = 0x40},
};